# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=64)),
                ('snippet', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
